name: cv-lysz210

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Compile assets
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run production

      - name: Setup PHP
        uses: php-actions/composer@v6
        with:
          php_version: '8'
          version: 2.x
      - name: Build cv files
        run: php artisan cv:gen pdf html --locale=en --locale=it
        env:
          MAIL_PERSONAL: ${{ secrets.MAIL_PERSONAL }}

      - name: Pulumi dependences
        working-directory: ./pulumi
        run: npm ci
      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: lysz210/cv.lysz210.name/dev
          work-dir: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
